directories:
  output: release
  buildResources: public
appId: com.emmasunny.cis
productName: Customer Information System
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - package.json
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/logo.ico
mac:
  target: dmg
  icon: public/logo.icns
  category: public.app-category.business
linux:
  target:
    - AppImage
    - deb
  icon: public/icon.png
  category: Office
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 39.2.7
